# Generated by Django 4.2.5 on 2023-10-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_oauth2token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="oauth2token",
            name="user",
        ),
        migrations.AddField(
            model_name="oauth2token",
            name="rc_user_id",
            field=models.PositiveIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
