# Generated by Django 4.2.5 on 2023-10-02 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_oauth2token_user_oauth2token_rc_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="oauth2token",
            name="name",
        ),
    ]
