# Generated by Django 4.2.5 on 2023-10-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_oauth2token_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Oauth2Token",
        ),
        migrations.AddField(
            model_name="user",
            name="access_token",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="expires_at",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="rc_user_id",
            field=models.PositiveIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="refresh_token",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="token_type",
            field=models.CharField(default="", max_length=40),
            preserve_default=False,
        ),
    ]
