# Generated by Django 4.2.5 on 2023-10-03 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_rfidtagscanlog_sound_user_rfid_tag_card_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sound",
            name="name",
        ),
    ]
