# Generated by Django 4.2.5 on 2023-10-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_sound_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rfidtagscanlog",
            options={"ordering": ["-scan_time"]},
        ),
        migrations.AlterModelOptions(
            name="sound",
            options={"ordering": ["file"]},
        ),
        migrations.AlterField(
            model_name="user",
            name="rfid_tag_card",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="rfid_tag_fc",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
