# Generated by Django 4.2.5 on 2024-08-30 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_user_sound_preference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="expires_at",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
